# Generated by Django 4.1 on 2022-12-08 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Libro", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=50, verbose_name="Apellido")),
                (
                    "nacionalidad",
                    models.CharField(max_length=50, verbose_name="Nacionalidad"),
                ),
                ("edad", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_prestamo", models.DateField(verbose_name="Fecha de Prestamo")),
                (
                    "fecha_devolucion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Devolucion"
                    ),
                ),
                ("estado", models.BooleanField()),
                (
                    "lector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Lector.lector"
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Libro.libro"
                    ),
                ),
            ],
        ),
    ]
